import home from "./home.js"
import dbz_ep2 from "./episodios/dragon-ball-z/ep2.js"
import dbz_ep2_lista from "./episodios/dragon-ball-z/ep2-lista.js"
import dbz_ep3 from "./episodios/dragon-ball-z/ep3.js"
import dbz_ep3_lista from "./episodios/dragon-ball-z/ep3-lista.js"
import dbz_ep4 from "./episodios/dragon-ball-z/ep4.js"
import dbz_ep4_lista from "./episodios/dragon-ball-z/ep4-lista.js"
import dbz_ep5 from "./episodios/dragon-ball-z/ep5.js"
import dbz_ep5_lista from "./episodios/dragon-ball-z/ep5-lista.js"
import dbz_ep6 from "./episodios/dragon-ball-z/ep6.js"
import dbz_ep6_lista from "./episodios/dragon-ball-z/ep6-lista.js"
import dbz_ep7 from "./episodios/dragon-ball-z/ep7.js"
import dbz_ep7_lista from "./episodios/dragon-ball-z/ep7-lista.js"
import dbz_ep8 from "./episodios/dragon-ball-z/ep8.js"
import dbz_ep8_lista from "./episodios/dragon-ball-z/ep8-lista.js"
import dbz_ep9 from "./episodios/dragon-ball-z/ep9.js"
import dbz_ep9_lista from "./episodios/dragon-ball-z/ep9-lista.js"
import dbz_ep10 from "./episodios/dragon-ball-z/ep10.js"
import dbz_ep10_lista from "./episodios/dragon-ball-z/ep10-lista.js"
import dbz_ep11 from "./episodios/dragon-ball-z/ep11.js"
import dbz_ep11_lista from "./episodios/dragon-ball-z/ep11-lista.js"
import dbz_ep12 from "./episodios/dragon-ball-z/ep12.js"
import dbz_ep12_lista from "./episodios/dragon-ball-z/ep12-lista.js"
import dbz_ep13 from "./episodios/dragon-ball-z/ep13.js"
import dbz_ep13_lista from "./episodios/dragon-ball-z/ep13-lista.js"
import dbz_ep14 from "./episodios/dragon-ball-z/ep14.js"
import dbz_ep14_lista from "./episodios/dragon-ball-z/ep14-lista.js"
import dbz_ep15 from "./episodios/dragon-ball-z/ep15.js"
import dbz_ep15_lista from "./episodios/dragon-ball-z/ep15-lista.js"
import dbz_ep16 from "./episodios/dragon-ball-z/ep16.js"
import dbz_ep16_lista from "./episodios/dragon-ball-z/ep16-lista.js"
import dbz_ep17 from "./episodios/dragon-ball-z/ep17.js"
import dbz_ep17_lista from "./episodios/dragon-ball-z/ep17-lista.js"
import dbz_ep18 from "./episodios/dragon-ball-z/ep18.js"
import dbz_ep18_lista from "./episodios/dragon-ball-z/ep18-lista.js"
import dbz_ep19 from "./episodios/dragon-ball-z/ep19.js"
import dbz_ep19_lista from "./episodios/dragon-ball-z/ep19-lista.js"
import dbz_ep20 from "./episodios/dragon-ball-z/ep20.js"
import dbz_ep20_lista from "./episodios/dragon-ball-z/ep20-lista.js"
import dbz_ep21 from "./episodios/dragon-ball-z/ep21.js"
import dbz_ep21_lista from "./episodios/dragon-ball-z/ep21-lista.js"
import dbz_ep22 from "./episodios/dragon-ball-z/ep22.js"
import dbz_ep22_lista from "./episodios/dragon-ball-z/ep22-lista.js"
import dbz_ep23 from "./episodios/dragon-ball-z/ep23.js"
import dbz_ep23_lista from "./episodios/dragon-ball-z/ep23-lista.js"
import dbz_ep24 from "./episodios/dragon-ball-z/ep24.js"
import dbz_ep24_lista from "./episodios/dragon-ball-z/ep24-lista.js"
import dbz_ep25 from "./episodios/dragon-ball-z/ep25.js"
import dbz_ep25_lista from "./episodios/dragon-ball-z/ep25-lista.js"
import dbz_ep26 from "./episodios/dragon-ball-z/ep26.js"
import dbz_ep26_lista from "./episodios/dragon-ball-z/ep26-lista.js"
import dbz_ep27 from "./episodios/dragon-ball-z/ep27.js"
import dbz_ep27_lista from "./episodios/dragon-ball-z/ep27-lista.js"
import dbz_ep28 from "./episodios/dragon-ball-z/ep28.js"
import dbz_ep28_lista from "./episodios/dragon-ball-z/ep28-lista.js"
import dbz_ep29 from "./episodios/dragon-ball-z/ep29.js"
import dbz_ep29_lista from "./episodios/dragon-ball-z/ep29-lista.js"
import dbz_ep30 from "./episodios/dragon-ball-z/ep30.js"
import dbz_ep30_lista from "./episodios/dragon-ball-z/ep30-lista.js"
import dbz_ep31 from "./episodios/dragon-ball-z/ep31.js"
import dbz_ep31_lista from "./episodios/dragon-ball-z/ep31-lista.js"
import dbz_ep32 from "./episodios/dragon-ball-z/ep32.js"
import dbz_ep32_lista from "./episodios/dragon-ball-z/ep32-lista.js"
import dbz_ep33 from "./episodios/dragon-ball-z/ep33.js"
import dbz_ep33_lista from "./episodios/dragon-ball-z/ep33-lista.js"
import dbz_ep34 from "./episodios/dragon-ball-z/ep34.js"
import dbz_ep34_lista from "./episodios/dragon-ball-z/ep34-lista.js"
import dbz_ep35 from "./episodios/dragon-ball-z/ep35.js"
import dbz_ep35_lista from "./episodios/dragon-ball-z/ep35-lista.js"
import dbz_ep36 from "./episodios/dragon-ball-z/ep36.js"
import dbz_ep36_lista from "./episodios/dragon-ball-z/ep36-lista.js"
import dbz_ep37 from "./episodios/dragon-ball-z/ep37.js"
import dbz_ep37_lista from "./episodios/dragon-ball-z/ep37-lista.js"
import dbz_ep38 from "./episodios/dragon-ball-z/ep38.js"
import dbz_ep38_lista from "./episodios/dragon-ball-z/ep38-lista.js"
import dbz_ep39 from "./episodios/dragon-ball-z/ep39.js"
import dbz_ep39_lista from "./episodios/dragon-ball-z/ep39-lista.js"
import dbz_ep40 from "./episodios/dragon-ball-z/ep40.js"
import dbz_ep40_lista from "./episodios/dragon-ball-z/ep40-lista.js"
import dbz_ep41 from "./episodios/dragon-ball-z/ep41.js"
import dbz_ep41_lista from "./episodios/dragon-ball-z/ep41-lista.js"
import dbz_ep42 from "./episodios/dragon-ball-z/ep42.js"
import dbz_ep42_lista from "./episodios/dragon-ball-z/ep42-lista.js"
import dbz_ep43 from "./episodios/dragon-ball-z/ep43.js"
import dbz_ep43_lista from "./episodios/dragon-ball-z/ep43-lista.js"
import dbz_ep44 from "./episodios/dragon-ball-z/ep44.js"
import dbz_ep44_lista from "./episodios/dragon-ball-z/ep44-lista.js"
import dbz_ep45 from "./episodios/dragon-ball-z/ep45.js"
import dbz_ep45_lista from "./episodios/dragon-ball-z/ep45-lista.js"
import dbz_ep46 from "./episodios/dragon-ball-z/ep46.js"
import dbz_ep46_lista from "./episodios/dragon-ball-z/ep46-lista.js"
import dbz_ep47 from "./episodios/dragon-ball-z/ep47.js"
import dbz_ep47_lista from "./episodios/dragon-ball-z/ep47-lista.js"
import dbz_ep48 from "./episodios/dragon-ball-z/ep48.js"
import dbz_ep48_lista from "./episodios/dragon-ball-z/ep48-lista.js"
import dbz_ep49 from "./episodios/dragon-ball-z/ep49.js"
import dbz_ep49_lista from "./episodios/dragon-ball-z/ep49-lista.js"
import dbz_ep50 from "./episodios/dragon-ball-z/ep50.js"
import dbz_ep50_lista from "./episodios/dragon-ball-z/ep50-lista.js"
import dbz_ep51 from "./episodios/dragon-ball-z/ep51.js"
import dbz_ep51_lista from "./episodios/dragon-ball-z/ep51-lista.js"
import dbz_ep52 from "./episodios/dragon-ball-z/ep52.js"
import dbz_ep52_lista from "./episodios/dragon-ball-z/ep52-lista.js"
import dbz_ep53 from "./episodios/dragon-ball-z/ep53.js"
import dbz_ep53_lista from "./episodios/dragon-ball-z/ep53-lista.js"
import dbz_ep54 from "./episodios/dragon-ball-z/ep54.js"
import dbz_ep54_lista from "./episodios/dragon-ball-z/ep54-lista.js"
import dbz_ep55 from "./episodios/dragon-ball-z/ep55.js"
import dbz_ep55_lista from "./episodios/dragon-ball-z/ep55-lista.js"
import dbz_ep56 from "./episodios/dragon-ball-z/ep56.js"
import dbz_ep56_lista from "./episodios/dragon-ball-z/ep56-lista.js"
import dbz_ep57 from "./episodios/dragon-ball-z/ep57.js"
import dbz_ep57_lista from "./episodios/dragon-ball-z/ep57-lista.js"
import dbz_ep58 from "./episodios/dragon-ball-z/ep58.js"
import dbz_ep58_lista from "./episodios/dragon-ball-z/ep58-lista.js"
import dbz_ep59 from "./episodios/dragon-ball-z/ep59.js"
import dbz_ep59_lista from "./episodios/dragon-ball-z/ep59-lista.js"
import dbz_ep60 from "./episodios/dragon-ball-z/ep60.js"
import dbz_ep60_lista from "./episodios/dragon-ball-z/ep60-lista.js"
import dbz_ep61 from "./episodios/dragon-ball-z/ep61.js"
import dbz_ep61_lista from "./episodios/dragon-ball-z/ep61-lista.js"
import dbz_ep62 from "./episodios/dragon-ball-z/ep62.js"
import dbz_ep62_lista from "./episodios/dragon-ball-z/ep62-lista.js"
import dbz_ep63 from "./episodios/dragon-ball-z/ep63.js"
import dbz_ep63_lista from "./episodios/dragon-ball-z/ep63-lista.js"
import dbz_ep64 from "./episodios/dragon-ball-z/ep64.js"
import dbz_ep64_lista from "./episodios/dragon-ball-z/ep64-lista.js"
import dbz_ep65 from "./episodios/dragon-ball-z/ep65.js"
import dbz_ep65_lista from "./episodios/dragon-ball-z/ep65-lista.js"
import dbz_ep66 from "./episodios/dragon-ball-z/ep66.js"
import dbz_ep66_lista from "./episodios/dragon-ball-z/ep66-lista.js"
import dbz_ep67 from "./episodios/dragon-ball-z/ep67.js"
import dbz_ep67_lista from "./episodios/dragon-ball-z/ep67-lista.js"
import dbz_ep68 from "./episodios/dragon-ball-z/ep68.js"
import dbz_ep68_lista from "./episodios/dragon-ball-z/ep68-lista.js"
import dbz_ep69 from "./episodios/dragon-ball-z/ep69.js"
import dbz_ep69_lista from "./episodios/dragon-ball-z/ep69-lista.js"
import dbz_ep70 from "./episodios/dragon-ball-z/ep70.js"
import dbz_ep70_lista from "./episodios/dragon-ball-z/ep70-lista.js"
import dbz_ep71 from "./episodios/dragon-ball-z/ep71.js"
import dbz_ep71_lista from "./episodios/dragon-ball-z/ep71-lista.js"
import dbz_ep72 from "./episodios/dragon-ball-z/ep72.js"
import dbz_ep72_lista from "./episodios/dragon-ball-z/ep72-lista.js"
import dbz_ep73 from "./episodios/dragon-ball-z/ep73.js"
import dbz_ep73_lista from "./episodios/dragon-ball-z/ep73-lista.js"
import dbz_ep74 from "./episodios/dragon-ball-z/ep74.js"
import dbz_ep74_lista from "./episodios/dragon-ball-z/ep74-lista.js"
import dbz_ep75 from "./episodios/dragon-ball-z/ep75.js"
import dbz_ep75_lista from "./episodios/dragon-ball-z/ep75-lista.js"
import dbz_ep76 from "./episodios/dragon-ball-z/ep76.js"
import dbz_ep76_lista from "./episodios/dragon-ball-z/ep76-lista.js"
import dbz_ep77 from "./episodios/dragon-ball-z/ep77.js"
import dbz_ep77_lista from "./episodios/dragon-ball-z/ep77-lista.js"
import dbz_ep78 from "./episodios/dragon-ball-z/ep78.js"
import dbz_ep78_lista from "./episodios/dragon-ball-z/ep78-lista.js"
import dbz_ep79 from "./episodios/dragon-ball-z/ep79.js"
import dbz_ep79_lista from "./episodios/dragon-ball-z/ep79-lista.js"
import dbz_ep80 from "./episodios/dragon-ball-z/ep80.js"
import dbz_ep80_lista from "./episodios/dragon-ball-z/ep80-lista.js"
import dbz_ep81 from "./episodios/dragon-ball-z/ep81.js"
import dbz_ep81_lista from "./episodios/dragon-ball-z/ep81-lista.js"
import dbz_ep82 from "./episodios/dragon-ball-z/ep82.js"
import dbz_ep82_lista from "./episodios/dragon-ball-z/ep82-lista.js"
import dbz_ep83 from "./episodios/dragon-ball-z/ep83.js"
import dbz_ep83_lista from "./episodios/dragon-ball-z/ep83-lista.js"
import dbz_ep84 from "./episodios/dragon-ball-z/ep84.js"
import dbz_ep84_lista from "./episodios/dragon-ball-z/ep84-lista.js"
import dbz_ep85 from "./episodios/dragon-ball-z/ep85.js"
import dbz_ep85_lista from "./episodios/dragon-ball-z/ep85-lista.js"
import dbz_ep86 from "./episodios/dragon-ball-z/ep86.js"
import dbz_ep86_lista from "./episodios/dragon-ball-z/ep86-lista.js"
import dbz_ep87 from "./episodios/dragon-ball-z/ep87.js"
import dbz_ep87_lista from "./episodios/dragon-ball-z/ep87-lista.js"
import dbz_ep88 from "./episodios/dragon-ball-z/ep88.js"
import dbz_ep88_lista from "./episodios/dragon-ball-z/ep88-lista.js"
import dbz_ep89 from "./episodios/dragon-ball-z/ep89.js"
import dbz_ep89_lista from "./episodios/dragon-ball-z/ep89-lista.js"
import dbz_ep90 from "./episodios/dragon-ball-z/ep90.js"
import dbz_ep90_lista from "./episodios/dragon-ball-z/ep90-lista.js"
import dbz_ep91 from "./episodios/dragon-ball-z/ep91.js"
import dbz_ep91_lista from "./episodios/dragon-ball-z/ep91-lista.js"
import dbz_ep92 from "./episodios/dragon-ball-z/ep92.js"
import dbz_ep92_lista from "./episodios/dragon-ball-z/ep92-lista.js"
import dbz_ep93 from "./episodios/dragon-ball-z/ep93.js"
import dbz_ep93_lista from "./episodios/dragon-ball-z/ep93-lista.js"
import dbz_ep94 from "./episodios/dragon-ball-z/ep94.js"
import dbz_ep94_lista from "./episodios/dragon-ball-z/ep94-lista.js"
import dbz_ep95 from "./episodios/dragon-ball-z/ep95.js"
import dbz_ep95_lista from "./episodios/dragon-ball-z/ep95-lista.js"
import dbz_ep96 from "./episodios/dragon-ball-z/ep96.js"
import dbz_ep96_lista from "./episodios/dragon-ball-z/ep96-lista.js"
import dbz_ep97 from "./episodios/dragon-ball-z/ep97.js"
import dbz_ep97_lista from "./episodios/dragon-ball-z/ep97-lista.js"
import dbz_ep98 from "./episodios/dragon-ball-z/ep98.js"
import dbz_ep98_lista from "./episodios/dragon-ball-z/ep98-lista.js"
import dbz_ep99 from "./episodios/dragon-ball-z/ep99.js"
import dbz_ep99_lista from "./episodios/dragon-ball-z/ep99-lista.js"
import dbz_ep100 from "./episodios/dragon-ball-z/ep100.js"
import dbz_ep100_lista from "./episodios/dragon-ball-z/ep100-lista.js"
import dbz_ep101 from "./episodios/dragon-ball-z/ep101.js"
import dbz_ep101_lista from "./episodios/dragon-ball-z/ep101-lista.js"
import dbz_ep102 from "./episodios/dragon-ball-z/ep102.js"
import dbz_ep102_lista from "./episodios/dragon-ball-z/ep102-lista.js"
import dbz_ep103 from "./episodios/dragon-ball-z/ep103.js"
import dbz_ep103_lista from "./episodios/dragon-ball-z/ep103-lista.js"
import dbz_ep104 from "./episodios/dragon-ball-z/ep104.js"
import dbz_ep104_lista from "./episodios/dragon-ball-z/ep104-lista.js"
import dbz_ep105 from "./episodios/dragon-ball-z/ep105.js"
import dbz_ep105_lista from "./episodios/dragon-ball-z/ep105-lista.js"
import dbz_ep106 from "./episodios/dragon-ball-z/ep106.js"
import dbz_ep106_lista from "./episodios/dragon-ball-z/ep106-lista.js"
import dbz_ep107 from "./episodios/dragon-ball-z/ep107.js"
import dbz_ep107_lista from "./episodios/dragon-ball-z/ep107-lista.js"
import dbz_ep108 from "./episodios/dragon-ball-z/ep108.js"
import dbz_ep108_lista from "./episodios/dragon-ball-z/ep108-lista.js"
import dbz_ep109 from "./episodios/dragon-ball-z/ep109.js"
import dbz_ep109_lista from "./episodios/dragon-ball-z/ep109-lista.js"
import dbz_ep110 from "./episodios/dragon-ball-z/ep110.js"
import dbz_ep110_lista from "./episodios/dragon-ball-z/ep110-lista.js"
import dbz_ep111 from "./episodios/dragon-ball-z/ep111.js"
import dbz_ep111_lista from "./episodios/dragon-ball-z/ep111-lista.js"
import dbz_ep112 from "./episodios/dragon-ball-z/ep112.js"
import dbz_ep112_lista from "./episodios/dragon-ball-z/ep112-lista.js"
import dbz_ep113 from "./episodios/dragon-ball-z/ep113.js"
import dbz_ep113_lista from "./episodios/dragon-ball-z/ep113-lista.js"
import dbz_ep114 from "./episodios/dragon-ball-z/ep114.js"
import dbz_ep114_lista from "./episodios/dragon-ball-z/ep114-lista.js"
import dbz_ep115 from "./episodios/dragon-ball-z/ep115.js"
import dbz_ep115_lista from "./episodios/dragon-ball-z/ep115-lista.js"
import dbz_ep116 from "./episodios/dragon-ball-z/ep116.js"
import dbz_ep116_lista from "./episodios/dragon-ball-z/ep116-lista.js"
import dbz_ep117 from "./episodios/dragon-ball-z/ep117.js"
import dbz_ep117_lista from "./episodios/dragon-ball-z/ep117-lista.js"
import dbz_ep118 from "./episodios/dragon-ball-z/ep118.js"
import dbz_ep118_lista from "./episodios/dragon-ball-z/ep118-lista.js"
import dbz_ep119 from "./episodios/dragon-ball-z/ep119.js"
import dbz_ep119_lista from "./episodios/dragon-ball-z/ep119-lista.js"
import dbz_ep120 from "./episodios/dragon-ball-z/ep120.js"
import dbz_ep120_lista from "./episodios/dragon-ball-z/ep120-lista.js"
import dbz_ep121 from "./episodios/dragon-ball-z/ep121.js"
import dbz_ep121_lista from "./episodios/dragon-ball-z/ep121-lista.js"
import dbz_ep122 from "./episodios/dragon-ball-z/ep122.js"
import dbz_ep122_lista from "./episodios/dragon-ball-z/ep122-lista.js"
import dbz_ep123 from "./episodios/dragon-ball-z/ep123.js"
import dbz_ep123_lista from "./episodios/dragon-ball-z/ep123-lista.js"
import dbz_ep124 from "./episodios/dragon-ball-z/ep124.js"
import dbz_ep124_lista from "./episodios/dragon-ball-z/ep124-lista.js"
import dbz_ep125 from "./episodios/dragon-ball-z/ep125.js"
import dbz_ep125_lista from "./episodios/dragon-ball-z/ep125-lista.js"
import dbz_ep126 from "./episodios/dragon-ball-z/ep126.js"
import dbz_ep126_lista from "./episodios/dragon-ball-z/ep126-lista.js"
import dbz_ep127 from "./episodios/dragon-ball-z/ep127.js"
import dbz_ep127_lista from "./episodios/dragon-ball-z/ep127-lista.js"
import dbz_ep128 from "./episodios/dragon-ball-z/ep128.js"
import dbz_ep128_lista from "./episodios/dragon-ball-z/ep128-lista.js"
import dbz_ep129 from "./episodios/dragon-ball-z/ep129.js"
import dbz_ep129_lista from "./episodios/dragon-ball-z/ep129-lista.js"
import dbz_ep130 from "./episodios/dragon-ball-z/ep130.js"
import dbz_ep130_lista from "./episodios/dragon-ball-z/ep130-lista.js"
import dbz_ep131 from "./episodios/dragon-ball-z/ep131.js"
import dbz_ep131_lista from "./episodios/dragon-ball-z/ep131-lista.js"
import dbz_ep132 from "./episodios/dragon-ball-z/ep132.js"
import dbz_ep132_lista from "./episodios/dragon-ball-z/ep132-lista.js"
import dbz_ep133 from "./episodios/dragon-ball-z/ep133.js"
import dbz_ep133_lista from "./episodios/dragon-ball-z/ep133-lista.js"
import dbz_ep134 from "./episodios/dragon-ball-z/ep134.js"
import dbz_ep134_lista from "./episodios/dragon-ball-z/ep134-lista.js"
import dbz_ep135 from "./episodios/dragon-ball-z/ep135.js"
import dbz_ep135_lista from "./episodios/dragon-ball-z/ep135-lista.js"
import dbz_ep136 from "./episodios/dragon-ball-z/ep136.js"
import dbz_ep136_lista from "./episodios/dragon-ball-z/ep136-lista.js"
import dbz_ep137 from "./episodios/dragon-ball-z/ep137.js"
import dbz_ep137_lista from "./episodios/dragon-ball-z/ep137-lista.js"
import dbz_ep138 from "./episodios/dragon-ball-z/ep138.js"
import dbz_ep138_lista from "./episodios/dragon-ball-z/ep138-lista.js"
import dbz_ep139 from "./episodios/dragon-ball-z/ep139.js"
import dbz_ep139_lista from "./episodios/dragon-ball-z/ep139-lista.js"
import dbz_ep140 from "./episodios/dragon-ball-z/ep140.js"
import dbz_ep140_lista from "./episodios/dragon-ball-z/ep140-lista.js"
import dbz_ep141 from "./episodios/dragon-ball-z/ep141.js"
import dbz_ep141_lista from "./episodios/dragon-ball-z/ep141-lista.js"
import dbz_ep142 from "./episodios/dragon-ball-z/ep142.js"
import dbz_ep142_lista from "./episodios/dragon-ball-z/ep142-lista.js"
import dbz_ep143 from "./episodios/dragon-ball-z/ep143.js"
import dbz_ep143_lista from "./episodios/dragon-ball-z/ep143-lista.js"
import dbz_ep144 from "./episodios/dragon-ball-z/ep144.js"
import dbz_ep144_lista from "./episodios/dragon-ball-z/ep144-lista.js"
import dbz_ep145 from "./episodios/dragon-ball-z/ep145.js"
import dbz_ep145_lista from "./episodios/dragon-ball-z/ep145-lista.js"
import dbz_ep146 from "./episodios/dragon-ball-z/ep146.js"
import dbz_ep146_lista from "./episodios/dragon-ball-z/ep146-lista.js"
import dbz_ep147 from "./episodios/dragon-ball-z/ep147.js"
import dbz_ep147_lista from "./episodios/dragon-ball-z/ep147-lista.js"
import dbz_ep148 from "./episodios/dragon-ball-z/ep148.js"
import dbz_ep148_lista from "./episodios/dragon-ball-z/ep148-lista.js"
import dbz_ep149 from "./episodios/dragon-ball-z/ep149.js"
import dbz_ep149_lista from "./episodios/dragon-ball-z/ep149-lista.js"
import dbz_ep150 from "./episodios/dragon-ball-z/ep150.js"
import dbz_ep150_lista from "./episodios/dragon-ball-z/ep150-lista.js"
import dbz_ep151 from "./episodios/dragon-ball-z/ep151.js"
import dbz_ep151_lista from "./episodios/dragon-ball-z/ep151-lista.js"
import dbz_ep152 from "./episodios/dragon-ball-z/ep152.js"
import dbz_ep152_lista from "./episodios/dragon-ball-z/ep152-lista.js"
import dbz_ep153 from "./episodios/dragon-ball-z/ep153.js"
import dbz_ep153_lista from "./episodios/dragon-ball-z/ep153-lista.js"
import dbz_ep154 from "./episodios/dragon-ball-z/ep154.js"
import dbz_ep154_lista from "./episodios/dragon-ball-z/ep154-lista.js"
import dbz_ep155 from "./episodios/dragon-ball-z/ep155.js"
import dbz_ep155_lista from "./episodios/dragon-ball-z/ep155-lista.js"
import dbz_ep156 from "./episodios/dragon-ball-z/ep156.js"
import dbz_ep156_lista from "./episodios/dragon-ball-z/ep156-lista.js"
import dbz_ep157 from "./episodios/dragon-ball-z/ep157.js"
import dbz_ep157_lista from "./episodios/dragon-ball-z/ep157-lista.js"
import dbz_ep158 from "./episodios/dragon-ball-z/ep158.js"
import dbz_ep158_lista from "./episodios/dragon-ball-z/ep158-lista.js"
import dbz_ep159 from "./episodios/dragon-ball-z/ep159.js"
import dbz_ep159_lista from "./episodios/dragon-ball-z/ep159-lista.js"
import dbz_ep160 from "./episodios/dragon-ball-z/ep160.js"
import dbz_ep160_lista from "./episodios/dragon-ball-z/ep160-lista.js"
import dbz_ep161 from "./episodios/dragon-ball-z/ep161.js"
import dbz_ep161_lista from "./episodios/dragon-ball-z/ep161-lista.js"
import dbz_ep162 from "./episodios/dragon-ball-z/ep162.js"
import dbz_ep162_lista from "./episodios/dragon-ball-z/ep162-lista.js"
import dbz_ep163 from "./episodios/dragon-ball-z/ep163.js"
import dbz_ep163_lista from "./episodios/dragon-ball-z/ep163-lista.js"
import dbz_ep164 from "./episodios/dragon-ball-z/ep164.js"
import dbz_ep164_lista from "./episodios/dragon-ball-z/ep164-lista.js"
import dbz_ep165 from "./episodios/dragon-ball-z/ep165.js"
import dbz_ep165_lista from "./episodios/dragon-ball-z/ep165-lista.js"
import dbz_ep166 from "./episodios/dragon-ball-z/ep166.js"
import dbz_ep166_lista from "./episodios/dragon-ball-z/ep166-lista.js"
import dbz_ep167 from "./episodios/dragon-ball-z/ep167.js"
import dbz_ep167_lista from "./episodios/dragon-ball-z/ep167-lista.js"
import dbz_ep168 from "./episodios/dragon-ball-z/ep168.js"
import dbz_ep168_lista from "./episodios/dragon-ball-z/ep168-lista.js"
import dbz_ep169 from "./episodios/dragon-ball-z/ep169.js"
import dbz_ep169_lista from "./episodios/dragon-ball-z/ep169-lista.js"
import dbz_ep170 from "./episodios/dragon-ball-z/ep170.js"
import dbz_ep170_lista from "./episodios/dragon-ball-z/ep170-lista.js"
import dbz_ep171 from "./episodios/dragon-ball-z/ep171.js"
import dbz_ep171_lista from "./episodios/dragon-ball-z/ep171-lista.js"
import dbz_ep172 from "./episodios/dragon-ball-z/ep172.js"
import dbz_ep172_lista from "./episodios/dragon-ball-z/ep172-lista.js"
import dbz_ep173 from "./episodios/dragon-ball-z/ep173.js"
import dbz_ep173_lista from "./episodios/dragon-ball-z/ep173-lista.js"
import dbz_ep174 from "./episodios/dragon-ball-z/ep174.js"
import dbz_ep174_lista from "./episodios/dragon-ball-z/ep174-lista.js"
import dbz_ep175 from "./episodios/dragon-ball-z/ep175.js"
import dbz_ep175_lista from "./episodios/dragon-ball-z/ep175-lista.js"
import dbz_ep176 from "./episodios/dragon-ball-z/ep176.js"
import dbz_ep176_lista from "./episodios/dragon-ball-z/ep176-lista.js"
import dbz_ep177 from "./episodios/dragon-ball-z/ep177.js"
import dbz_ep177_lista from "./episodios/dragon-ball-z/ep177-lista.js"
import dbz_ep178 from "./episodios/dragon-ball-z/ep178.js"
import dbz_ep178_lista from "./episodios/dragon-ball-z/ep178-lista.js"
import dbz_ep179 from "./episodios/dragon-ball-z/ep179.js"
import dbz_ep179_lista from "./episodios/dragon-ball-z/ep179-lista.js"
import dbz_ep180 from "./episodios/dragon-ball-z/ep180.js"
import dbz_ep180_lista from "./episodios/dragon-ball-z/ep180-lista.js"
import dbz_ep181 from "./episodios/dragon-ball-z/ep181.js"
import dbz_ep181_lista from "./episodios/dragon-ball-z/ep181-lista.js"
import dbz_ep182 from "./episodios/dragon-ball-z/ep182.js"
import dbz_ep182_lista from "./episodios/dragon-ball-z/ep182-lista.js"
import dbz_ep183 from "./episodios/dragon-ball-z/ep183.js"
import dbz_ep183_lista from "./episodios/dragon-ball-z/ep183-lista.js"
import dbz_ep184 from "./episodios/dragon-ball-z/ep184.js"
import dbz_ep184_lista from "./episodios/dragon-ball-z/ep184-lista.js"
import dbz_ep185 from "./episodios/dragon-ball-z/ep185.js"
import dbz_ep185_lista from "./episodios/dragon-ball-z/ep185-lista.js"
import dbz_ep186 from "./episodios/dragon-ball-z/ep186.js"
import dbz_ep186_lista from "./episodios/dragon-ball-z/ep186-lista.js"
import dbz_ep187 from "./episodios/dragon-ball-z/ep187.js"
import dbz_ep187_lista from "./episodios/dragon-ball-z/ep187-lista.js"
import dbz_ep188 from "./episodios/dragon-ball-z/ep188.js"
import dbz_ep188_lista from "./episodios/dragon-ball-z/ep188-lista.js"
import dbz_ep189 from "./episodios/dragon-ball-z/ep189.js"
import dbz_ep189_lista from "./episodios/dragon-ball-z/ep189-lista.js"
import dbz_ep190 from "./episodios/dragon-ball-z/ep190.js"
import dbz_ep190_lista from "./episodios/dragon-ball-z/ep190-lista.js"
import dbz_ep191 from "./episodios/dragon-ball-z/ep191.js"
import dbz_ep191_lista from "./episodios/dragon-ball-z/ep191-lista.js"
import dbz_ep192 from "./episodios/dragon-ball-z/ep192.js"
import dbz_ep192_lista from "./episodios/dragon-ball-z/ep192-lista.js"
import dbz_ep193 from "./episodios/dragon-ball-z/ep193.js"
import dbz_ep193_lista from "./episodios/dragon-ball-z/ep193-lista.js"
import dbz_ep194 from "./episodios/dragon-ball-z/ep194.js"
import dbz_ep194_lista from "./episodios/dragon-ball-z/ep194-lista.js"
import dbz_ep195 from "./episodios/dragon-ball-z/ep195.js"
import dbz_ep195_lista from "./episodios/dragon-ball-z/ep195-lista.js"
import dbz_ep196 from "./episodios/dragon-ball-z/ep196.js"
import dbz_ep196_lista from "./episodios/dragon-ball-z/ep196-lista.js"
import dbz_ep197 from "./episodios/dragon-ball-z/ep197.js"
import dbz_ep197_lista from "./episodios/dragon-ball-z/ep197-lista.js"
import dbz_ep198 from "./episodios/dragon-ball-z/ep198.js"
import dbz_ep198_lista from "./episodios/dragon-ball-z/ep198-lista.js"
import dbz_ep199 from "./episodios/dragon-ball-z/ep199.js"
import dbz_ep199_lista from "./episodios/dragon-ball-z/ep199-lista.js"
import dbz_ep200 from "./episodios/dragon-ball-z/ep200.js"
import dbz_ep200_lista from "./episodios/dragon-ball-z/ep200-lista.js"
import dbz_ep201 from "./episodios/dragon-ball-z/ep201.js"
import dbz_ep201_lista from "./episodios/dragon-ball-z/ep201-lista.js"
import dbz_ep202 from "./episodios/dragon-ball-z/ep202.js"
import dbz_ep202_lista from "./episodios/dragon-ball-z/ep202-lista.js"
import dbz_ep203 from "./episodios/dragon-ball-z/ep203.js"
import dbz_ep203_lista from "./episodios/dragon-ball-z/ep203-lista.js"
import dbz_ep204 from "./episodios/dragon-ball-z/ep204.js"
import dbz_ep204_lista from "./episodios/dragon-ball-z/ep204-lista.js"
import dbz_ep205 from "./episodios/dragon-ball-z/ep205.js"
import dbz_ep205_lista from "./episodios/dragon-ball-z/ep205-lista.js"
import dbz_ep206 from "./episodios/dragon-ball-z/ep206.js"
import dbz_ep206_lista from "./episodios/dragon-ball-z/ep206-lista.js"
import dbz_ep207 from "./episodios/dragon-ball-z/ep207.js"
import dbz_ep207_lista from "./episodios/dragon-ball-z/ep207-lista.js"
import dbz_ep208 from "./episodios/dragon-ball-z/ep208.js"
import dbz_ep208_lista from "./episodios/dragon-ball-z/ep208-lista.js"
import dbz_ep209 from "./episodios/dragon-ball-z/ep209.js"
import dbz_ep209_lista from "./episodios/dragon-ball-z/ep209-lista.js"
import dbz_ep210 from "./episodios/dragon-ball-z/ep210.js"
import dbz_ep210_lista from "./episodios/dragon-ball-z/ep210-lista.js"
import dbz_ep211 from "./episodios/dragon-ball-z/ep211.js"
import dbz_ep211_lista from "./episodios/dragon-ball-z/ep211-lista.js"
import dbz_ep212 from "./episodios/dragon-ball-z/ep212.js"
import dbz_ep212_lista from "./episodios/dragon-ball-z/ep212-lista.js"
import dbz_ep213 from "./episodios/dragon-ball-z/ep213.js"
import dbz_ep213_lista from "./episodios/dragon-ball-z/ep213-lista.js"
import dbz_ep214 from "./episodios/dragon-ball-z/ep214.js"
import dbz_ep214_lista from "./episodios/dragon-ball-z/ep214-lista.js"
import dbz_ep215 from "./episodios/dragon-ball-z/ep215.js"
import dbz_ep215_lista from "./episodios/dragon-ball-z/ep215-lista.js"
import dbz_ep216 from "./episodios/dragon-ball-z/ep216.js"
import dbz_ep216_lista from "./episodios/dragon-ball-z/ep216-lista.js"
import dbz_ep217 from "./episodios/dragon-ball-z/ep217.js"
import dbz_ep217_lista from "./episodios/dragon-ball-z/ep217-lista.js"
import dbz_ep218 from "./episodios/dragon-ball-z/ep218.js"
import dbz_ep218_lista from "./episodios/dragon-ball-z/ep218-lista.js"
import dbz_ep219 from "./episodios/dragon-ball-z/ep219.js"
import dbz_ep219_lista from "./episodios/dragon-ball-z/ep219-lista.js"
import dbz_ep220 from "./episodios/dragon-ball-z/ep220.js"
import dbz_ep220_lista from "./episodios/dragon-ball-z/ep220-lista.js"
import dbz_ep221 from "./episodios/dragon-ball-z/ep221.js"
import dbz_ep221_lista from "./episodios/dragon-ball-z/ep221-lista.js"
import dbz_ep222 from "./episodios/dragon-ball-z/ep222.js"
import dbz_ep222_lista from "./episodios/dragon-ball-z/ep222-lista.js"
import dbz_ep223 from "./episodios/dragon-ball-z/ep223.js"
import dbz_ep223_lista from "./episodios/dragon-ball-z/ep223-lista.js"
import dbz_ep224 from "./episodios/dragon-ball-z/ep224.js"
import dbz_ep224_lista from "./episodios/dragon-ball-z/ep224-lista.js"
import dbz_ep225 from "./episodios/dragon-ball-z/ep225.js"
import dbz_ep225_lista from "./episodios/dragon-ball-z/ep225-lista.js"
import dbz_ep226 from "./episodios/dragon-ball-z/ep226.js"
import dbz_ep226_lista from "./episodios/dragon-ball-z/ep226-lista.js"
import dbz_ep227 from "./episodios/dragon-ball-z/ep227.js"
import dbz_ep227_lista from "./episodios/dragon-ball-z/ep227-lista.js"
import dbz_ep228 from "./episodios/dragon-ball-z/ep228.js"
import dbz_ep228_lista from "./episodios/dragon-ball-z/ep228-lista.js"
import dbz_ep229 from "./episodios/dragon-ball-z/ep229.js"
import dbz_ep229_lista from "./episodios/dragon-ball-z/ep229-lista.js"
import dbz_ep230 from "./episodios/dragon-ball-z/ep230.js"
import dbz_ep230_lista from "./episodios/dragon-ball-z/ep230-lista.js"
import dbz_ep231 from "./episodios/dragon-ball-z/ep231.js"
import dbz_ep231_lista from "./episodios/dragon-ball-z/ep231-lista.js"
import dbz_ep232 from "./episodios/dragon-ball-z/ep232.js"
import dbz_ep232_lista from "./episodios/dragon-ball-z/ep232-lista.js"
import dbz_ep233 from "./episodios/dragon-ball-z/ep233.js"
import dbz_ep233_lista from "./episodios/dragon-ball-z/ep233-lista.js"
import dbz_ep234 from "./episodios/dragon-ball-z/ep234.js"
import dbz_ep234_lista from "./episodios/dragon-ball-z/ep234-lista.js"
import dbz_ep235 from "./episodios/dragon-ball-z/ep235.js"
import dbz_ep235_lista from "./episodios/dragon-ball-z/ep235-lista.js"
import dbz_ep236 from "./episodios/dragon-ball-z/ep236.js"
import dbz_ep236_lista from "./episodios/dragon-ball-z/ep236-lista.js"
import dbz_ep237 from "./episodios/dragon-ball-z/ep237.js"
import dbz_ep237_lista from "./episodios/dragon-ball-z/ep237-lista.js"
import dbz_ep238 from "./episodios/dragon-ball-z/ep238.js"
import dbz_ep238_lista from "./episodios/dragon-ball-z/ep238-lista.js"
import dbz_ep239 from "./episodios/dragon-ball-z/ep239.js"
import dbz_ep239_lista from "./episodios/dragon-ball-z/ep239-lista.js"
import dbz_ep240 from "./episodios/dragon-ball-z/ep240.js"
import dbz_ep240_lista from "./episodios/dragon-ball-z/ep240-lista.js"
import dbz_ep241 from "./episodios/dragon-ball-z/ep241.js"
import dbz_ep241_lista from "./episodios/dragon-ball-z/ep241-lista.js"
import dbz_ep242 from "./episodios/dragon-ball-z/ep242.js"
import dbz_ep242_lista from "./episodios/dragon-ball-z/ep242-lista.js"
import dbz_ep243 from "./episodios/dragon-ball-z/ep243.js"
import dbz_ep243_lista from "./episodios/dragon-ball-z/ep243-lista.js"
import dbz_ep244 from "./episodios/dragon-ball-z/ep244.js"
import dbz_ep244_lista from "./episodios/dragon-ball-z/ep244-lista.js"
import dbz_ep245 from "./episodios/dragon-ball-z/ep245.js"
import dbz_ep245_lista from "./episodios/dragon-ball-z/ep245-lista.js"
import dbz_ep246 from "./episodios/dragon-ball-z/ep246.js"
import dbz_ep246_lista from "./episodios/dragon-ball-z/ep246-lista.js"
import dbz_ep247 from "./episodios/dragon-ball-z/ep247.js"
import dbz_ep247_lista from "./episodios/dragon-ball-z/ep247-lista.js"
import dbz_ep248 from "./episodios/dragon-ball-z/ep248.js"
import dbz_ep248_lista from "./episodios/dragon-ball-z/ep248-lista.js"
import dbz_ep249 from "./episodios/dragon-ball-z/ep249.js"
import dbz_ep249_lista from "./episodios/dragon-ball-z/ep249-lista.js"
import dbz_ep250 from "./episodios/dragon-ball-z/ep250.js"
import dbz_ep250_lista from "./episodios/dragon-ball-z/ep250-lista.js"
import dbz_ep251 from "./episodios/dragon-ball-z/ep251.js"
import dbz_ep251_lista from "./episodios/dragon-ball-z/ep251-lista.js"
import dbz_ep252 from "./episodios/dragon-ball-z/ep252.js"

const main = document.querySelector('#root')

const init = () => {
    window.addEventListener("hashchange", () => {
        main.innerHTML = "";
        switch(window.location.hash){
            case "#home":
                    main.appendChild(home());
            break
            case "#ep2":
                main.appendChild(dbz_ep2());
            break
            case "#ep2-lista":
                main.appendChild(dbz_ep2_lista());
            break
            case "#ep3":
                main.appendChild(dbz_ep3());
            break
            case "#ep3-lista":
                main.appendChild(dbz_ep3_lista());
            break
            case "#ep4":
                main.appendChild(dbz_ep4());
            break
            case "#ep4-lista":
                main.appendChild(dbz_ep4_lista());
            break
            case "#ep5":
                main.appendChild(dbz_ep5());
            break
            case "#ep5-lista":
                main.appendChild(dbz_ep5_lista());
            break
            case "#ep6":
                main.appendChild(dbz_ep6());
            break
            case "#ep6-lista":
                main.appendChild(dbz_ep6_lista());
            break
            case "#ep7":
                main.appendChild(dbz_ep7());
            break
            case "#ep7-lista":
                main.appendChild(dbz_ep7_lista());
            break
            case "#ep8":
                main.appendChild(dbz_ep8());
            break
            case "#ep8-lista":
                main.appendChild(dbz_ep8_lista());
            break
            case "#ep9":
                main.appendChild(dbz_ep9());
            break
            case "#ep9-lista":
                main.appendChild(dbz_ep9_lista());
            break
            case "#ep10":
                main.appendChild(dbz_ep10());
            break
            case "#ep10-lista":
                main.appendChild(dbz_ep10_lista());
            break
            case "#ep11":
                main.appendChild(dbz_ep11());
            break
            case "#ep11-lista":
                main.appendChild(dbz_ep11_lista());
            break
        }
    })
}

window.addEventListener("load", () => {
    main.appendChild(home())
    init();
})